# Comparing 10 different Regression Models

In [54]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.metrics import r2_score, root_mean_squared_error

In [19]:
df = load_diabetes(as_frame=True)
df

{'data':           age       sex       bmi        bp        s1        s2        s3  \
 0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
 1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
 2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
 3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
 4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
 ..        ...       ...       ...       ...       ...       ...       ...
 437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
 438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
 439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
 440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
 441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

            s4        s5        s6
 0   -0.002592  0.019907 -0.017646
 1   -0.039493 -0.068332 -0.092204
 2   -0.002592  0.002861 -0.025930
 3    0.034309  0.022688 -0.009362
 4   -0.002592 -0.031988 -0.046641
 ..        ...       ...       ...
 437 -0.002592  0.031193  0.007207
 438  0.034309 -0.018114  0.044485
 439 -0.011080 -0.046883  0.015491
 440  0.026560  0.044529 -0.025930
 441 -0.039493 -0.004222  0.003064

 [442 rows x 10 columns],
 'target': 0      151.0
 1       75.0
 2      141.0
 3      206.0
 4      135.0
        ...
 437    178.0
 438    104.0
 439    132.0
 440    220.0
 441     57.0
 Name: target, Length: 442, dtype: float64,
 'frame':           age       sex       bmi        bp        s1        s2        s3  \
 0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
 1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
 2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
 3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
 4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
 ..        ...       ...       ...       ...       ...       ...       ...
 437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
 438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
 439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
 440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
 441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

            s4        s5        s6  target
 0   -0.002592  0.019907 -0.017646   151.0
 1   -0.039493 -0.068332 -0.092204    75.0
 2   -0.002592  0.002861 -0.025930   141.0
 3    0.034309  0.022688 -0.009362   206.0
 4   -0.002592 -0.031988 -0.046641   135.0
 ..        ...       ...       ...     ...
 437 -0.002592  0.031193  0.007207   178.0
 438  0.034309 -0.018114  0.044485   104.0
 439 -0.011080 -0.046883  0.015491   132.0
 440  0.026560  0.044529 -0.025930   220.0
 441 -0.039493 -0.004222  0.003064    57.0

 [442 rows x 11 columns],
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [32]:
data = fetch_california_housing(as_frame=True)
data

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude
 0        -122.23
 1        -122.22
 2        -122.24
 3        -122.25
 4        -122.25
 ...          ...
 20635    -121.09
 20636    -121.21
 20637    -121.22
 20638    -121.32
 20639    -121.24

 [20640 rows x 8 columns],
 'target': 0        4.526
 1        3.585
 2        3.521
 3        3.413
 4        3.422
          ...
 20635    0.781
 20636    0.771
 20637    0.923
 20638    0.847
 20639    0.894
 Name: MedHouseVal, Length: 20640, dtype: float64,
 'frame':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude  MedHouseVal
 0        -122.23        4.526
 1        -122.22        3.585
 2        -122.24        3.521
 3        -122.25        3.413
 4        -122.25        3.422
 ...          ...          ...
 20635    -121.09        0.781
 20636    -121.21        0.771
 20637    -121.22        0.923
 20638    -121.32        0.847
 20639    -121.24        0.894

 [20640 rows x 9 columns],
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [33]:
X = data.data
y = data.target

In [34]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [35]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [36]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    ExtraTreesRegressor
)
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

In [37]:
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.01),
    "Decision Tree": DecisionTreeRegressor(),
    "RandomForestRegressor": RandomForestRegressor(n_estimators=100),
    "ExtraTreesRegressor": ExtraTreesRegressor(n_estimators=100),
    "GradientBoostingRegressor": GradientBoostingRegressor(),
    "KNeighborsRegressor": KNeighborsRegressor(n_neighbors=5),
    "SVR": SVR(),
    "Neural Network": MLPRegressor(hidden_layer_sizes=(100,50), max_iter=500)
}

In [38]:
models

{'LinearRegression': LinearRegression(),
 'Ridge': Ridge(),
 'Lasso': Lasso(alpha=0.01),
 'Decision Tree': DecisionTreeRegressor(),
 'RandomForestRegressor': RandomForestRegressor(),
 'ExtraTreesRegressor': ExtraTreesRegressor(),
 'GradientBoostingRegressor': GradientBoostingRegressor(),
 'KNeighborsRegressor': KNeighborsRegressor(),
 'SVR': SVR(),
 'Neural Network': MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500)}

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [40]:
results = []

for name, model in models.items():
    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

    pipeline.fit(X_train, y_train)
    preds = pipeline.predict(X_test)
    
    r2 = r2_score(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    
    results.append({
        "Model": name,
        "R2 Score": r2,
        "RMSE": rmse,
    })

In [28]:
results

[{'Model': 'LinearRegression',
  'R2 Score': 0.3546301090355529,
  'RMSE': np.float64(62.34219135059027)},
 {'Model': 'Ridge',
  'R2 Score': 0.35322101646431514,
  'RMSE': np.float64(62.4102128230753)},
 {'Model': 'Lasso',
  'R2 Score': 0.3543674329533839,
  'RMSE': np.float64(62.354877204734784)},
 {'Model': 'Decision Tree',
  'R2 Score': -0.07025851856470022,
  'RMSE': np.float64(80.2827167374247)},
 {'Model': 'RandomForestRegressor',
  'R2 Score': 0.3355216716056062,
  'RMSE': np.float64(63.258388545301365)},
 {'Model': 'ExtraTreesRegressor',
  'R2 Score': 0.31327318379986513,
  'RMSE': np.float64(64.30869803297708)},
 {'Model': 'GradientBoostingRegressor',
  'R2 Score': 0.3152325344115553,
  'RMSE': np.float64(64.21689057067664)},
 {'Model': 'KNeighborsRegressor',
  'R2 Score': 0.19321717884710377,
  'RMSE': np.float64(69.70373259072036)},
 {'Model': 'SVR',
  'R2 Score': 0.08650769378831036,
  'RMSE': np.float64(74.17032137259149)},
 {'Model': 'Neural Network',
  'R2 Score': 0.4098875392782837,
  'RMSE': np.float64(59.613566677822284)}]

In [41]:
results_df = pd.DataFrame(results).sort_values(by="R2 Score", ascending=False)

In [42]:
results_df

                       Model  R2 Score      RMSE
5        ExtraTreesRegressor  0.827763  0.479638
4      RandomForestRegressor  0.827040  0.480644
9             Neural Network  0.821070  0.488869
6  GradientBoostingRegressor  0.801293  0.515179
8                        SVR  0.750739  0.577003
7        KNeighborsRegressor  0.701345  0.631591
3              Decision Tree  0.645672  0.687945
1                      Ridge  0.617942  0.714357
0           LinearRegression  0.617934  0.714365
2                      Lasso  0.614316  0.717739

# Same ML Problem with and without Feature Engineering

Dataset: California Housing

Model: Linear Regression

Linear Regression is interesting because when Feature Engineering works on a simple Model like LR you could transfer it to mor complex models

Metric: Root Mean Squared Error (RMSE)

In [43]:
data

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude
 0        -122.23
 1        -122.22
 2        -122.24
 3        -122.25
 4        -122.25
 ...          ...
 20635    -121.09
 20636    -121.21
 20637    -121.22
 20638    -121.32
 20639    -121.24

 [20640 rows x 8 columns],
 'target': 0        4.526
 1        3.585
 2        3.521
 3        3.413
 4        3.422
          ...
 20635    0.781
 20636    0.771
 20637    0.923
 20638    0.847
 20639    0.894
 Name: MedHouseVal, Length: 20640, dtype: float64,
 'frame':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude  MedHouseVal
 0        -122.23        4.526
 1        -122.22        3.585
 2        -122.24        3.521
 3        -122.25        3.413
 4        -122.25        3.422
 ...          ...          ...
 20635    -121.09        0.781
 20636    -121.21        0.771
 20637    -121.22        0.923
 20638    -121.32        0.847
 20639    -121.24        0.894

 [20640 rows x 9 columns],
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [46]:
df = data.frame
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [47]:
X = df.drop("MedHouseVal", axis=1)
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [48]:
y = df["MedHouseVal"]

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [52]:
baseline_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

baseline_pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [53]:
y_pred_baseline = baseline_pipeline.predict(X_test)

In [57]:
rmse_baseline = root_mean_squared_error(y_test, y_pred_baseline)
rmse_baseline

0.7501086645358636

In [58]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [60]:
X_fe = X.copy()

X_fe["BedroomsPerRoom"] = X_fe["AveBedrms"] / X_fe["AveRooms"]

In [61]:
X_fe["PopulationDividedByMedInc"] = X_fe["Population"] / X_fe["MedInc"]

In [62]:
X_train_fe, X_test_fe, y_train_fe, y_test_fe = train_test_split(X_fe, y, test_size=0.2)

In [63]:
fe_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

fe_pipeline.fit(X_train_fe, y_train_fe)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [64]:
y_pred_fe = fe_pipeline.predict(X_test_fe)

In [66]:
rmse_fe = root_mean_squared_error(y_test_fe, y_pred_fe)
rmse_fe

0.6865815438366625

In [67]:
print(rmse_baseline)
print(rmse_fe)

0.7501086645358636
0.6865815438366625

As we can see the through minimal Feature Engineering the models performance improved when exposing meaningful relationships

## Same as above with the best model from the Test

Dataset: California Housing
Model: ExtraTreesRegressor
Metric: Root Mean Squared Error (RMSE)

In [68]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [69]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [70]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [72]:
tree_baseline_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", ExtraTreesRegressor(n_estimators=100))
])

tree_baseline_pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', ExtraTreesRegressor())])

In [74]:
y_pred_tree_baseline = tree_baseline_pipeline.predict(X_test)

rmse_baseline_tree = root_mean_squared_error(y_test, y_pred_tree_baseline)

In [75]:
rmse_baseline_tree

0.4896286543117339

In [76]:
tree_fe_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", ExtraTreesRegressor(n_estimators=100))
])

tree_fe_pipeline.fit(X_train_fe, y_train_fe)

Pipeline(steps=[('scaler', StandardScaler()), ('model', ExtraTreesRegressor())])

In [77]:
y_pred_fe_tree = tree_fe_pipeline.predict(X_test_fe)
rmse_fe_tree = root_mean_squared_error(y_test_fe, y_pred_fe_tree)
rmse_fe_tree

0.4829624274636265

In [78]:
print(rmse_baseline_tree)
print(rmse_fe_tree)

0.4896286543117339
0.4829624274636265

Even though the models baseline was already good it improved a bit through feature Engineering, which shows how effective it can be

These experiments show that feature engineering is more powerful than just switching to a more compley Algorithm